CREATE TABLE IF NOT EXISTS propertyLinks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  propertyId INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(500) NOT NULL,
  showOnLandingPage BOOLEAN DEFAULT TRUE,
  sortOrder INT DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  INDEX idx_propertyId (propertyId)
);
