CREATE TABLE `activities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`activityType` enum('note','email','call','meeting','viewing','other') NOT NULL,
	`subject` varchar(255),
	`content` text,
	`propertyId` int,
	`contactId` int,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `activities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `appointments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`appointmentType` enum('viewing','meeting','phone_call','other') DEFAULT 'viewing',
	`startTime` timestamp NOT NULL,
	`endTime` timestamp NOT NULL,
	`propertyId` int,
	`contactId` int,
	`status` enum('scheduled','completed','cancelled','no_show') DEFAULT 'scheduled',
	`notes` text,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `appointments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contactType` enum('buyer','seller','tenant','landlord','interested','other') NOT NULL,
	`salutation` enum('mr','ms','diverse'),
	`firstName` varchar(100),
	`lastName` varchar(100) NOT NULL,
	`company` varchar(255),
	`email` varchar(320),
	`phone` varchar(50),
	`mobile` varchar(50),
	`street` varchar(255),
	`houseNumber` varchar(50),
	`zipCode` varchar(20),
	`city` varchar(100),
	`country` varchar(100),
	`notes` text,
	`source` varchar(100),
	`brevoContactId` varchar(100),
	`lastSyncedToBrevo` timestamp,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`documentType` enum('contract','expose','floorplan','energy_certificate','other') DEFAULT 'other',
	`fileUrl` text,
	`nasPath` text,
	`fileName` varchar(255),
	`fileSize` int,
	`mimeType` varchar(100),
	`propertyId` int,
	`contactId` int,
	`uploadedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int,
	`source` varchar(100),
	`firstName` varchar(100),
	`lastName` varchar(100),
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`message` text,
	`status` enum('new','contacted','qualified','converted','rejected') DEFAULT 'new',
	`convertedToContactId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`propertyType` enum('apartment','house','commercial','land','parking','other') NOT NULL,
	`marketingType` enum('sale','rent','lease') NOT NULL,
	`status` enum('available','reserved','sold','rented','inactive') NOT NULL DEFAULT 'available',
	`street` varchar(255),
	`houseNumber` varchar(50),
	`zipCode` varchar(20),
	`city` varchar(100),
	`country` varchar(100) DEFAULT 'Deutschland',
	`livingArea` int,
	`plotArea` int,
	`rooms` int,
	`bedrooms` int,
	`bathrooms` int,
	`floor` int,
	`totalFloors` int,
	`price` int,
	`pricePerSqm` int,
	`additionalCosts` int,
	`heatingCosts` int,
	`deposit` int,
	`hasBalcony` boolean DEFAULT false,
	`hasTerrace` boolean DEFAULT false,
	`hasGarden` boolean DEFAULT false,
	`hasElevator` boolean DEFAULT false,
	`hasParking` boolean DEFAULT false,
	`hasBasement` boolean DEFAULT false,
	`energyClass` varchar(10),
	`energyConsumption` int,
	`heatingType` varchar(100),
	`yearBuilt` int,
	`condition` enum('new','renovated','good','needs_renovation','demolished'),
	`availableFrom` timestamp,
	`contactPersonId` int,
	`hasLandingPage` boolean DEFAULT false,
	`landingPageSlug` varchar(255),
	`landingPagePublished` boolean DEFAULT false,
	`viewCount` int DEFAULT 0,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `properties_id` PRIMARY KEY(`id`),
	CONSTRAINT `properties_landingPageSlug_unique` UNIQUE(`landingPageSlug`)
);
--> statement-breakpoint
CREATE TABLE `propertyImages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`imageUrl` text NOT NULL,
	`nasPath` text,
	`title` varchar(255),
	`description` text,
	`imageType` enum('main','exterior','interior','floorplan','map','other') DEFAULT 'other',
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `propertyImages_id` PRIMARY KEY(`id`)
);
